import blockContent from './blockContent'
import category from './category'
import tags from './tags'
import author from './author'
import social from './social'
import portfolio from './portfolio'
import blog from './blog'
import about from './about'
import education from './education'
import experience from './experience'
import expertise from './expertise'
import services from './services'
import certificate from './certificate'
import skills from './skills'
import serviceBlog from './serviceBlog'
import tutorial from './tutorial'
import topic from './topic'


export const schemaTypes = [blockContent, about, social, education, experience, expertise, skills, services, certificate, author, category, tags, blog, portfolio, serviceBlog, topic, tutorial]
